name: ansible-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ansible-lint
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - run: python -m pip install --upgrade pip
      - run: pip install ansible-lint ansible
      - run: ansible-lint --version
      - run: ansible-playbook test.yml --syntax-check
      - run: ansible-lint test.yml
